parameters:
- name: action
  type: string
  default: 'add' # or 'remove'

steps:
- ${{ if eq(parameters.action, 'add') }}:
  - task: AzureCLI@2
    displayName: 'Add Azure SQL Firewall Rule'
    inputs:
      azureSubscription: VSEng-DDBuildScripts
      scriptType: ps
      scriptLocation: 'inlineScript'
      inlineScript: |
        $agent_ip = Invoke-RestMethod -Uri "https://api.ipify.org"
        Write-Host "Agent IP: $agent_ip"
        az sql server firewall-rule create `
          --resource-group $(resourceGroup) `
          --server $(azureSqlServer) `
          --name $(ruleName) `
          --start-ip-address $agent_ip `
          --end-ip-address $agent_ip
    continueOnError: false

- ${{ else }}:
  - task: AzureCLI@2
    displayName: 'Remove Azure SQL Firewall Rule'
    inputs:
      azureSubscription: VSEng-DDBuildScripts
      scriptType: ps
      scriptLocation: 'inlineScript'
      inlineScript: |
        az sql server firewall-rule delete `
          --resource-group $(resourceGroup) `
          --server $(azureSqlServer) `
          --name $(ruleName)
    condition: always()