parameters:
- name: LogType
  type: string
  default: 'Information'

variables:
- template: /template/variables.yml@self

name: $(date:yyyyMMdd)$(rev:.r)

pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: stage
  jobs:
  - job: Display_Variable
    steps:
    - pwsh: |
        Import-Module $(SourceFolder)\VSRepo-Guidelines.psm1
        Test-LogFileModule -LogType ${{ parameters.LogType }}
      displayName: 'Display Variable'