variables:
- name: SourceFolder
  value: $(Build.SourcesDirectory)


pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  - job: TestVariables
    displayName: Test Variables
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
      displayName: 'Install .NET 8 SDK'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.slnx'

    - script: dotnet build $(SourceFolder)/LoggingCommands/LoggingCommands/LoggingCommands.csproj --configuration Release
      displayName: 'Build Project'

    - script: dotnet run --project $(SourceFolder)/LoggingCommands/LoggingCommands/LoggingCommands.csproj --configuration Release
      displayName: Run LoggingCommands Solution
