trigger: none
pr: none
pool:
  vmImage: 'windows-latest'
stages:
- stage: stage
  jobs:
  - job: Phase_1
    steps:
    - task: NuGetAuthenticate@1
    - task: NuGetCommand@2
      displayName: 'NuGet Install VSEng.PI Package'
      inputs:
        restoreSolution: packages.vsengpi.config
        feedsToUse: config
        nugetConfigPath: nuget.config
        noCache: true
        restoreDirectory: '$(Agent.BuildDirectory)\IntegrationScripts'

    - pwsh: |
        $success = $false
        Get-ChildItem -Path '$(Agent.BuildDirectory)\IntegrationScripts' -Directory -Filter 'VSEng.PI*' | ForEach-Object {
            $from = $_.FullName
            $to = '$(SourceFolder)\VSEng.PI'
            Write-Host "From: $from"
            Write-Host "Destination: $to"
        
            for ($i=0; $i -lt 3; $i++) {
                try {
                    if ((Get-Item $from).Attributes -match "ReadOnly") {
                        Write-Host "Cleanup ReadOnly Attribute"
                        Set-ItemProperty $from -Name Attributes -Value ((Get-Item $from).Attributes -band -17)
                    }
                    Move-Item $from $to -Force
                    $success = $true
                    Write-Host "Move-Item succeeded"
                    break
                } catch {
                    Write-Warning "Move-Item failed: $_. Try #$($i+1)"
                    Start-Sleep -Seconds 1
                }
            }
            if (-not $success) {
                throw "Move-Item failed after retries"
            }
        }
      displayName: 'Move VSEng.PI Folder'
      condition: succeeded()
