variables:
- template: /template/variables.yml@self
  parameters:
    SolutionName: ConsoleApp1

name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none
pool:
  vmImage: 'windows-latest'
stages:
- stage: stage
  displayName: 'Console App 1'
  jobs:
  - job: Phase_1
    displayName: DDBuildScripts-ConsoleApp1
    steps:
    - pwsh: |
        Write-Host "Get-Env: $(Get-ChildItem env:)"
      displayName: 'Get Environment Variables'