pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  - job: TestVariables
    displayName: Test Variables
    steps:
    - pwsh: |
        # Find all .sln/.slnx file names
        $solutions = Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Include "*.sln", "*.slnx" | 
                Where-Object { $_.FullName -notmatch '\\(bin|obj|packages|node_modules)\\' } |
                ForEach-Object { $_.Name } |
                Join-String -Separator ','
        Write-Host "Found solutions: $solutions"
        Write-Host "##vso[task.setvariable variable=Solutions]$solutions"
      displayName: 'Find All Solutions'
      continueOnError: false

    - template: /template/build-solution.yml
      parameters:
        SolutionName: '${{ variables.Solutions }}'