parameters:
  - name: PRId
    type: string
    default: ' '
  - name: OrgName
    type: string
    default: 'DevDiv'
  - name: ProjectName
    type: string
    default: 'DevDiv'
  - name: RepoName
    type: string
    default: 'VS'
  - name: VSBaseUrl
    type: string
    default: 'https://dev.azure.com'
  - name: ExpiredDays
    type: string
    default: '90'
  - name: MaxPRToAbandon
    type: string
    default: '50'

trigger: none

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  - job: Scan 
    displayName: 'Scan Solutions'
    steps:
    - pwsh: |
        $paramString = "OrgName:${{ parameters.OrgName }} `
        ProjectName:${{ parameters.ProjectName }} `
        RepoName:${{ parameters.RepoName }} `
        VsUri:${{ parameters.VSBaseUrl }} `
        ExpirePROlderThan:${{ parameters.ExpiredDays }} `
        MaxPRToAbandon:${{ parameters.MaxPRToAbandon }}"

        $prId = "${{ parameters.PRId }}".Trim()
        if ($prId -eq "") {
          $extrParm = ""
          Write-Host "PRId is not provided, defaulting to empty string."
        } else {
          $extrParm = " PRId:$prId"
          Write-Host "PRId is provided: $prId"
        }

        Write-Host "Running: $(SolutionName).exe $paramString$extrParm AccessToken:***"
      displayName: 'Test'