variables:
- template: /template/variables.yml@self
- name: RepoName
  value: $(vsRepo)

name: $(date:yyyyMMdd)$(rev:.r)

pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  - job: TestVariables
    displayName: Test Variables
    steps:
    # - template: /template/InstallNugetPackage.yml@self
    #   parameters:
    #     PackageName: '$(packageName)'

    - script: |
        echo "Repository Name: $(RepoName)"
      displayName: 'Display Variable'