variables:
- template: /template/variables.yml@self
  parameters:
    SolutionName: ConsoleApp1

name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none
pool:
  vmImage: 'windows-latest'
stages:
- stage: stage
  displayName: 'Console App 1'
  jobs:
  - job: Phase_1
    displayName: DDBuildScripts-ConsoleApp1
    steps:
    - task: NuGetToolInstaller@0
      displayName: Use NuGet
      inputs:
        checkLatest: true
    - task: NuGetCommand@2
      displayName: NuGet restore
      inputs:
        solution: '**/$(SolutionName).csproj'
        feedRestore: $(EngineeringFeedGUID)
    - task: VSBuild@1
      displayName: 'Build solution - $(SolutionName)'
      inputs:
        solution: '**/$(SolutionName).slnx'
        platform: $(BuildPlatform)
        configuration: $(BuildConfiguration)