parameters:
- name: PIVersion
  type: string
  default: ' '
- name: MailerVersion
  type: string
  default: ' '

variables:
- template: /template/variables.yml@self
  parameters:
    VSEng.PI.Version: $(PIVersion)
    VSEng.Mailer.Version: $(MailerVersion)
- name: RepoName
  value: $(vsRepo)

name: $(date:yyyyMMdd)$(rev:.r)

pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: stage
  jobs:
  - job: Display_Variable
    steps:
    - script: |
        echo "Repository Name: $(RepoName)"
        echo "PI Version: $(VSEng.PI.Version)"
        echo "Mailer Version: $(VSEng.Mailer.Version)"
      displayName: 'Display Variable'