parameters:
- name: PIVersion
  type: string
  default: ' '
- name: MailerVersion
  type: string
  default: ' '

variables:
- template: /template/variables.yml@self
  parameters:
    VSEng_PI_Version: ${{ parameters.PIVersion }}
    VSEng_Mailer_Version: ${{ parameters.MailerVersion }}
- name: RepoName
  value: $(vsRepo)

name: $(date:yyyyMMdd)$(rev:.r)

pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: stage
  jobs:
  - job: Display_Variable
    steps:
    - script: |
        echo "Repository Name: $(RepoName)"
        echo "PI Version: $(VSEng_PI_Version)"
        echo "Mailer Version: $(VSEng_Mailer_Version)"
      displayName: 'Display Variable'
    - template: /template/install-nuget-package.yml@self
      parameters:
        packageName: ${{ variables.VSEng_Mailer }}
        pkgVersion: ${{ variables.VSEng_Mailer_Version }}