pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  - job: Scan
    displayName: 'Scan Solutions'
    steps:
    - pwsh: |
        # Find all .sln/.slnx file names
        $solutions = Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Include "*.sln", "*.slnx" |
            Where-Object { $_.FullName -notmatch '\\(bin|obj|packages|node_modules)\\' } |
                ForEach-Object { $_.Name } |
                Join-String -Separator ','

        if ($solutions.Count -eq 0) {
          Write-Host "##[error]No solution files found"
          exit 1
        }

        Write-Host "##vso[task.setVariable variable=Solutions;isOutput=true]$solutions"
      name: scan
      displayName: 'Find All Solutions'

  - job: Build
    displayName: 'Build'
    dependsOn: Scan
    variables:
      solutionList: $[ dependencies.Scan.outputs['scan.Solutions'] ]
    steps:
    - template: /template/build-solution.yml
      parameters:
        SolutionName: $(solutionList)