variables:
- name: SolutionName
  value: Testing
- name: SourceFolder
  value: $(Build.SourcesDirectory)

pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  - job: TestVariables
    displayName: Test Variables
    steps:
    - pwsh: |
        Import-Module $(SourceFolder)\LogFile.psm1 -Force

        Write-LogMessage -Message "Normal"
      displayName: 'Run LogFile Tests Information'
    - pwsh: |
        Import-Module $(SourceFolder)\LogFile.psm1 -Force

        Write-LogMessage -Message "Test warning" -LogType 'Warning'
      displayName: 'Run LogFile Tests Warning'
    - pwsh: |
        Import-Module $(SourceFolder)\LogFile.psm1 -Force

        Write-LogMessage -Message "Test Error" -LogType 'Error'
      displayName: 'Run LogFile Tests Error'
    - pwsh: |
        Import-Module $(SourceFolder)\LogFile.psm1 -Force

        Write-LogMessage -Message "Normal" -LogType 'Information'
      displayName: 'Run LogFile Tests Information'
      condition: always()