parameters:
  - name: OrgName
    type: string
    default: 'DevDiv'
  - name: ProjectName
    type: string
    default: ' '

trigger: none

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  - job: Scan 
    displayName: 'Scan Solutions'
    steps:
    - pwsh: |
        Write-Host "OrgName: ${{ parameters.OrgName }}TTT"
        Write-Host "ProjectName: ${{ parameters.ProjectName }}TTT"
      displayName: 'Test'