parameters:
- name: PkgVersion
  type: string
  displayName: "specific package version for Microsoft.Build. If empty, the test will fail."
  default: '17.13.19'

trigger: none
pr: none
pool:
  vmImage: 'windows-latest'
stages:
- stage: stage
  jobs:
  - job: Phase_1
    steps:
    - pwsh: |
        Write-Host $env:NUGET_AUTH_TOKEN
      displayName: Check Env
    - task: NuGetCommand@2
      displayName: 'NuGet Install Microsoft.Build Package'
      inputs:
        command: custom
        arguments: 'install Microsoft.Build -version ${{ parameters.PkgVersion }} -ConfigFile $(Build.SourcesDirectory)\Nuget.config -OutputDirectory $(Agent.BuildDirectory)\IntegrationScripts'

