parameters:
- name: PackageName
  type: string
  default: 'Azure.Core'

name: $(date:yyyyMMdd)$(rev:.r)

variables:
- template: /template/variables.yml@self

pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  - job: TestVariables
    displayName: Test Variables
    steps:
    - template: /template/InstallNugetPackage.yml@self
      parameters:
        PackageName: '${{ parameters.PackageName }}'

    - script: |
        echo "Repository Name: $(vsRepo)"
      DisplayName: 'Display Variable'