parameters:
- name: PkgVersion
  type: string
  default: ' '

trigger: none
pr: none
pool:
  vmImage: 'windows-latest'
stages:
- stage: stage
  jobs:
  - job: Phase_1
    steps:
    - pwsh: |
        Write-Host $env:NUGET_AUTH_TOKEN
      displayName: Check Env
    - ${{ if eq(parameters.PkgVersion, ' ') }}:
      - task: NuGetCommand@2
        displayName: 'NuGet Install Microsoft.Build Package'
        inputs:
          arguments: 'install Microsoft.Build -ConfigFile $(Build.SourcesDirectory)\Nuget.config -OutputDirectory $(Agent.BuildDirectory)\IntegrationScripts'
    - ${{ if ne(parameters.PkgVersion, ' ') }}:
      - task: NuGetCommand@2
        displayName: 'NuGet Install Microsoft.Build Package ${{ parameters.PkgVersion }}'
        inputs:
          arguments: 'install Microsoft.Build -Version ${{ parameters.PkgVersion }} -ConfigFile $(Build.SourcesDirectory)\Nuget.config -OutputDirectory $(Agent.BuildDirectory)\IntegrationScripts'
