variables:
- name: PackageName
  value: 'Azure.Core'
- name: SourceFolder
  value: $(Build.SourcesDirectory)

name: $(date:yyyyMMdd)$(rev:.r)

variables:
- template: /template/variables.yml@self

pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  - job: TestVariables
    displayName: Test Variables
    steps:
    - template: /template/InstallNugetPackage.yml@self
      parameters:
        PackageName: '$(PackageName)'

    - script: |
        echo "Repository Name: $(vsRepo)"
      DisplayName: 'Display Variable'