pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  - job: TestVariables
    displayName: Test Variables
    steps:

    - task: PowerShell@2
      displayName: Find MSBuild
      inputs:
        targetType: inline
        script: |
          $vswherePath = "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $instances = & $vswherePath @("-utf8", "-version", "[15.0,19.0)", "-latest", "-format", "json") | ConvertFrom-Json
          if ($instances.Length -eq 0)
          {
            Write-Warning "Could not find any complete instances of Visual Studio."
          }
          elseif ($instances.Length -eq 1)
          {
            $instance = $instances[0]
            Write-Host "Found only one instance of Visual Studio: $($instance.installationPath)"
          }
          else
          {
            $instance = $instances[0]
            Write-Host "Found more than one instance of Visual Studio, defaulting to: $($instance.installationPath)"
            Write-Host "Other instances:"
            foreach ($ins in $instances)
            {
              Write-Host "$ins.installationPath"
            }
          }
          $msbuildPath = Join-Path $instance.installationPath "MSBuild\Current\Bin\amd64\msbuild.exe"
          Write-Host "Setting MSBuild path to: $msbuildPath"
          Write-Host "##vso[task.setvariable variable=msbuild18Path;]$msbuildPath"

    - task: NuGetToolInstaller@1 
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(Build.SourcesDirectory)/DotnetFramework472/DotnetFramework472.slnx'

    - task: MSBuild@1
      inputs:
        solution: '$(Build.SourcesDirectory)/DotnetFramework472/DotnetFramework472.slnx'
        msbuildLocationMethod: 'location'
        msbuildLocation: $(msbuild18Path)
        msbuildArguments: '/bl:$(Build.SourcesDirectory)\Logs\msbuild.binlog;ProjectImports=None  /p:Configuration=Debug /p:Platform="Any CPU" /p:OutputPath=$(Build.SourcesDirectory)\Output'

    - powershell: Get-ChildItem -LiteralPath "$(Build.SourcesDirectory)" -Recurse
      displayName: 'List all files in workspace'

    # - script: |
    #     cd src/MyApp/bin/Release
    #     MyApp.exe arg1 arg2
    #   displayName: 'Run .NET Framework EXE'
    #   workingDirectory: $(Build.ArtifactStagingDirectory)\Output
