pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  displayName: Test Stage
  jobs:
  # Job 1: 扫描所有 solution，输出 matrix JSON
  - job: Scan
    displayName: 'Scan Solutions'
    steps:
    - pwsh: |
        $solutions = Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Include "*.sln", "*.slnx" |
            Where-Object { $_.FullName -notmatch '\\(bin|obj|packages|node_modules)\\' }

        if ($solutions.Count -eq 0) {
          Write-Host "##[error]No solution files found"
          exit 1
        }

        # 构建 matrix JSON: { "Solution1": { "SolutionName": "A.sln" }, "Solution2": { "SolutionName": "B.sln" } }
        $matrix = [ordered]@{}
        foreach ($sln in $solutions) {
          $key = $sln.BaseName -replace '[^a-zA-Z0-9]', '_'
          $matrix[$key] = @{ SolutionName = $sln.Name }
        }
        $json = $matrix | ConvertTo-Json -Compress
        Write-Host "Matrix JSON: $json"
        Write-Host "##vso[task.setVariable variable=matrix;isOutput=true]$json"
      name: scan
      displayName: 'Find All Solutions'

  # Job 2: 动态 matrix — 每个 solution 一组独立的 task
  - job: Build
    displayName: 'Build'
    dependsOn: Scan
    strategy:
      matrix: $[ dependencies.Scan.outputs['scan.matrix'] ]
    steps:
    - pwsh: |
        Write-Host "Building solution: $(SolutionName)"
      displayName: 'Build $(SolutionName)'