<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net481;net6.0</TargetFrameworks>
    <LangVersion>10.0</LangVersion>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="VSEng.Mailer" />
    <PackageReference Include="VSEng.PI" />
  </ItemGroup>
</Project>