parameters:
- name: SolutionName
  type: string
  default: ' '

steps:
- task: NuGetToolInstaller@1
  displayName: Use NuGet
  inputs:
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet Restore (${{ parameters.SolutionName }})'
  inputs:
    restoreSolution: '**/${{ parameters.SolutionName }}'
    feedsToUse: 'config'
    nugetConfigPath: Nuget.config
    includeNuGetOrg: false
  continueOnError: false

- task: VSBuild@1
  displayName: 'Build ${{ parameters.SolutionName }}'
  inputs:
    solution: '**/${{ parameters.SolutionName }}'
    platform: $(BuildPlatform)
    Configuration: $(BuildConfiguration)
    msbuildArgs: >
      /bl:$(Build.ArtifactStagingDirectory)\Logs\${{ parameters.SolutionName }}.binlog;ProjectImports=None
      /p:OutputPath=$(OutputFolder)
  continueOnError: false