parameters:
  SDKVersion: ''

steps:
- task: NuGetToolInstaller@1
  displayName: Use NuGet
  inputs:
    checkLatest: true

- pwsh: |
    Write-Host "Setting up environment variables for PackageLoader solution"
    Write-Host "##vso[task.setvariable variable=AssemblyPath]$(OutputFolder)"
  displayName: 'Set Assembly Path Variable'
  condition: and(succeeded(), eq(variables['SolutionName'], 'PackageLoader'))