# variables.yml - Azure Pipeline Variables Template
# 
# This template defines common variables and parameters used across the GitHygieneTools pipelines.

parameters:
# Define the name of the solution to build. This should match the name of the .sln or .slnx file in the repository.
- name: SolutionName
  type: string
  default: ' '
# Define the version of VSEngMailer to use in the build process. This can be overridden when the pipeline is run.
- name: VSEngMailerVersion
  type: string
  default: '1.0.*'

variables:
# Common Settings
- name: VSRepo
  value: VS
- name: RECONRepo
  value: RECON
- name: VSWhatsNewContentRepo
  value: VSWhatsNewContent

- name: ProjectName
  value: DevDiv
- name: SetupBackupRemote
  value: true

# Build Settings
- name: SolutionName
  value: ${{ parameters.SolutionName }}
- name: SourceFolder
  value: $(Build.SourcesDirectory)\src
- name: OutputFolder
  value: $(SourceFolder)\$(SolutionName)\output
- name: BuildPlatform
  value: 'Any CPU'
- name: BuildConfiguration
  value: 'Debug'

# Service Connections
- name: GitHygieneSC
  value: VSEng-GitHygieneSC
- name: VSEngMailer
  value: VSEngMailer

# Packages
- name: VSEng_PI
  value: VSEng.PI
- name: VSEng_Mailer
  value: VSEng.Mailer
- name: VSEngMailerVersion
  value: ${{ parameters.VSEngMailerVersion }}

# Abandon Expired PR Settings
- name: VSBaseUrl
  value: 'https://dev.azure.com'

# Deleted Branch Checking Settings
- name: ArtifactName
  value: GitHygieneOutput
- name: TargetPath
  value: $(Build.ArtifactStagingDirectory)\$(ArtifactName)

# Stale Branch Cleanup Settings
- name: VSStaleAge
  value: 180
- name: VSLimitUserBranchCount
  value: 2000
- name: VSMaxBranchesToPurge
  value: 300

- name: RECONStaleAge
  value: 60
- name: RECONLimitUserBranchCount
  value: 5000
- name: RECONMaxBranchesToPurge
  value: 300

- name: VSWhatsNewContentStaleAge
  value: 60
- name: VSWhatsNewContentLimitUserBranchCount
  value: 5000
- name: VSWhatsNewContentMaxBranchesToPurge
  value: 300

# Old Tag Cleanup Settings
- name: ExemptBranches
  value: d14vsuldr
- name: MonthsToKeep
  value: 6
- name: DropUrl
  value: 'https://devdiv.artifacts.visualstudio.com'
- name: LocalDropClientPath
  value: '$(SourceFolder)\DropClient\drop.exe'
- name: LocalDropsFilePath
  value: '$(SourceFolder)\drops.json'
- name: MaxCleanupCount
  value: 300