parameters:
- name: KEYWORDS
  type: string
  displayName: 'Keywords for Xcode monitoring (comma-separated)'
  default: 'Xcode'

variables:
- template: /src/azure-pipelines/template/variables.yml@self
  parameters:
    SolutionName: PackageLoader

name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none
pool:
  vmImage: 'windows-latest'
stages:
- stage: stage
  displayName: 'Console App 1'
  jobs:
  - job: Phase_1
    displayName: TempTest
    steps:
    - template: /src/azure-pipelines/template/build-solution.yml@self
      parameters:
        SolutionName: '$(SolutionName).slnx'

    - script: |
        $(SolutionName).exe
      displayName: 'Run $(SolutionName) EXE'
      workingDirectory: $(SourceFolder)\Output
      env:
        KEYWORDS: ${{ parameters.KEYWORDS }}