parameters:
- name: TestParam
  type: string

variables:
- name: TestVar
  value: 1

name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

pool:
  vmImage: 'windows-latest'
stages:
- stage: stage
  displayName: 'Test'
  jobs:
  - job: Phase_1
    displayName: DDBuildScripts-Test
    steps:
    # - pwsh: |
    #     Write-Host "Environment Variables:"
    #     Get-ChildItem Env: | ForEach-Object { Write-Host "$($_.Name)=$($_.Value)" }
    #   displayName: 'Print Environment Variables'
    - pwsh: |
        Write-Host "Parameters:"
        Write-Host "  TestParam: ${{ parameters.TestParam }}"
        Write-Host "Variables:"
        Write-Host "  TestVar: $(TestVar)"
        Write-Host "  TestVar2: $(TestVar2)"
      displayName: 'Print parameters'