parameters:
- name: Account
  type: string
  default: 'DevDiv'
- name: Project
  type: string
  default: 'DevDiv'
- name: BuildId
  type: string
  default: ''

name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

pool:
  vmImage: 'windows-latest'
stages:
- stage: stage
  displayName: 'Test'
  jobs:
  - job: Phase_1
    displayName: DDBuildScripts-Test
    steps:
    - pwsh: |
        Write-Host "Parameters:"
        Write-Host "  Account: ${{ parameters.Account }}"
        Write-Host "  Project: ${{ parameters.Project }}"
        Write-Host "  BuildId: ${{ parameters.BuildId }}"
        Write-Host "  WorkflowBranch: ${{ parameters.WorkflowBranch }}"
      displayName: 'Print parameters'